import type { Metadata } from 'next'
import AuthProvider from './Provider'
import NavBar from '../components/NavBar';
import Footer from '@/components/Footer';
import { Inter, MuseoModerno } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const museo = MuseoModerno({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'The Game Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">   
      <body className={museo.className}>
      <NavBar />
        <AuthProvider>
          {children}
        </AuthProvider>
      <Footer/>
      </body>
    </html>
  )
}
